IMG = {
    "wheelchair": "https://images.unsplash.com/photo-1642680936843-b09109c69104?w=800&q=80",
    "mobility": "https://images.pexels.com/photos/6194680/pexels-photo-6194680.jpeg?auto=compress&w=800",
    "walker": "https://images.pexels.com/photos/7551617/pexels-photo-7551617.jpeg?auto=compress&w=800",
    "brace": "https://images.pexels.com/photos/7446990/pexels-photo-7446990.jpeg?auto=compress&w=800",
    "diabetes": "https://images.pexels.com/photos/4386466/pexels-photo-4386466.jpeg?auto=compress&w=800",
    "wound": "https://images.pexels.com/photos/4047186/pexels-photo-4047186.jpeg?auto=compress&w=800",
    "medical": "https://images.pexels.com/photos/4057758/pexels-photo-4057758.jpeg?auto=compress&w=800",
    "supplies": "https://images.pexels.com/photos/5938358/pexels-photo-5938358.jpeg?auto=compress&w=800",
    "ortho": "https://images.pexels.com/photos/6941883/pexels-photo-6941883.jpeg?auto=compress&w=800",
    "care": "https://images.pexels.com/photos/16364307/pexels-photo-16364307.jpeg?auto=compress&w=800",
    "doctor": "https://images.pexels.com/photos/7578810/pexels-photo-7578810.jpeg?auto=compress&w=800",
}

CATEGORIES = [
    {"slug": "mobility-aids", "name": "Mobility Aids", "name_es": "Ayudas de Movilidad", "description": "Wheelchairs, walkers, rollators, canes and scooters to keep you moving safely.", "description_es": "Sillas de ruedas, andadores, rollators, bastones y scooters para mantenerlo en movimiento con seguridad.", "image": IMG["mobility"], "order": 1},
    {"slug": "orthotics", "name": "Orthotics", "name_es": "Ortesis", "description": "Braces and supports for knees, backs, ankles and wrists — fitted for comfort.", "description_es": "Soportes y aparatos ortopédicos para rodillas, espalda, tobillos y muñecas.", "image": IMG["ortho"], "order": 2},
    {"slug": "diabetes-care", "name": "Diabetes Care", "name_es": "Cuidado de la Diabetes", "description": "Glucose monitors, test strips, CGMs and diabetic footwear — resupply reminders available.", "description_es": "Monitores de glucosa, tiras reactivas, MCG y calzado para diabéticos.", "image": IMG["diabetes"], "order": 3},
    {"slug": "wound-care", "name": "Wound Care", "name_es": "Cuidado de Heridas", "description": "Advanced dressings, bandages and wound care supplies delivered to your door.", "description_es": "Apósitos avanzados, vendajes y suministros para el cuidado de heridas.", "image": IMG["wound"], "order": 4},
]

PRODUCTS = [
    # Mobility Aids
    {"slug": "standard-wheelchair", "name": "Standard Manual Wheelchair", "category_slug": "mobility-aids", "coverage": "insurance", "price": None, "image": IMG["wheelchair"], "featured": True, "in_stock": True,
     "description": "Lightweight steel-frame wheelchair with padded armrests and swing-away footrests. Typically covered by Medicare Part B with a doctor's prescription.",
     "features": ["300 lb weight capacity", "18\" seat width", "Foldable for transport", "Medicare Part B eligible"]},
    {"slug": "transport-wheelchair", "name": "Lightweight Transport Wheelchair", "category_slug": "mobility-aids", "coverage": "insurance", "price": None, "image": IMG["mobility"], "featured": False, "in_stock": True,
     "description": "Companion-propelled transport chair, only 19 lbs. Ideal for appointments and outings.",
     "features": ["19 lb aluminum frame", "Folds flat in seconds", "Loop-lock hand brakes"]},
    {"slug": "rollator-walker", "name": "4-Wheel Rollator with Seat", "category_slug": "mobility-aids", "coverage": "insurance", "price": None, "image": IMG["walker"], "featured": True, "in_stock": True,
     "description": "Stable rollator with built-in seat, backrest and storage pouch. Covered by most insurance plans with prescription.",
     "features": ["Padded seat & backrest", "8\" wheels for outdoor use", "Height-adjustable handles", "Storage pouch included"]},
    {"slug": "folding-walker", "name": "Two-Button Folding Walker", "category_slug": "mobility-aids", "coverage": "insurance", "price": None, "image": IMG["walker"], "featured": False, "in_stock": True,
     "description": "Classic folding walker with 5\" front wheels. Medicare-covered with doctor's order.",
     "features": ["Folds with two buttons", "Adjustable height 32\"–39\"", "350 lb capacity"]},
    {"slug": "quad-cane", "name": "Quad Cane with Offset Handle", "category_slug": "mobility-aids", "coverage": "cash", "price": 34.99, "image": IMG["medical"], "featured": False, "in_stock": True,
     "description": "Four-point base cane for extra stability. Available for direct purchase — no prescription needed.",
     "features": ["Stands on its own", "Ergonomic offset handle", "Adjustable 28\"–37\""]},
    {"slug": "knee-scooter", "name": "Steerable Knee Scooter", "category_slug": "mobility-aids", "coverage": "cash", "price": 189.00, "image": IMG["mobility"], "featured": False, "in_stock": True,
     "description": "Comfortable alternative to crutches after foot or ankle surgery.",
     "features": ["Steerable front wheels", "Dual hand brakes", "Folds for car trunk"]},
    # Orthotics
    {"slug": "hinged-knee-brace", "name": "Hinged Knee Brace", "category_slug": "orthotics", "coverage": "insurance", "price": None, "image": IMG["brace"], "featured": True, "in_stock": True,
     "description": "Bilateral hinged support for ligament injuries and post-op recovery. Covered by Medicare with physician documentation.",
     "features": ["Bilateral aluminum hinges", "Breathable neoprene", "Open-patella design", "L1833 HCPCS code"]},
    {"slug": "back-brace-lso", "name": "LSO Back Brace", "category_slug": "orthotics", "coverage": "insurance", "price": None, "image": IMG["ortho"], "featured": False, "in_stock": True,
     "description": "Lumbar-sacral orthosis for lower back pain and post-surgical support. Insurance covered with prescription.",
     "features": ["Rigid posterior panel", "Adjustable compression", "Fits waist 28\"–50\""]},
    {"slug": "ankle-stabilizer", "name": "Lace-Up Ankle Stabilizer", "category_slug": "orthotics", "coverage": "cash", "price": 29.99, "image": IMG["brace"], "featured": False, "in_stock": True,
     "description": "Figure-8 strapping system for sprains and chronic instability.",
     "features": ["Fits left or right", "Wear inside shoes", "Machine washable"]},
    {"slug": "wrist-splint", "name": "Carpal Tunnel Wrist Splint", "category_slug": "orthotics", "coverage": "cash", "price": 24.99, "image": IMG["ortho"], "featured": False, "in_stock": True,
     "description": "Night-time wrist support with removable palmar stay.",
     "features": ["Removable metal stay", "Breathable fabric", "Left and right versions"]},
    {"slug": "cervical-collar", "name": "Soft Cervical Collar", "category_slug": "orthotics", "coverage": "insurance", "price": None, "image": IMG["medical"], "featured": False, "in_stock": True,
     "description": "Foam neck support for whiplash and cervical strain. Covered with physician order.",
     "features": ["1\" contoured foam", "Hook-and-loop closure", "Latex free"]},
    # Diabetes Care
    {"slug": "glucose-monitor-kit", "name": "Blood Glucose Monitor Kit", "category_slug": "diabetes-care", "coverage": "insurance", "price": None, "image": IMG["diabetes"], "featured": True, "in_stock": True,
     "description": "Complete testing kit: meter, lancing device, 10 lancets and carrying case. Covered by Medicare Part B for people with diabetes.",
     "features": ["5-second results", "300-reading memory", "No coding required", "Medicare Part B eligible"]},
    {"slug": "test-strips-100", "name": "Glucose Test Strips (100 ct)", "category_slug": "diabetes-care", "coverage": "insurance", "price": None, "image": IMG["diabetes"], "featured": False, "in_stock": True,
     "description": "Monthly resupply of test strips. Set up automatic resupply reminders so you never run out.",
     "features": ["100 strips per box", "Resupply eligible", "Auto-reminder available"]},
    {"slug": "cgm-sensor", "name": "Continuous Glucose Monitor Sensors", "category_slug": "diabetes-care", "coverage": "insurance", "price": None, "image": IMG["supplies"], "featured": True, "in_stock": True,
     "description": "14-day wear CGM sensors. Covered by Medicare for qualifying patients on insulin.",
     "features": ["14-day wear time", "No fingersticks needed", "Smartphone compatible", "Resupply eligible"]},
    {"slug": "diabetic-shoes", "name": "Therapeutic Diabetic Shoes", "category_slug": "diabetes-care", "coverage": "insurance", "price": None, "image": IMG["medical"], "featured": False, "in_stock": True,
     "description": "Extra-depth therapeutic footwear with custom inserts. Medicare covers one pair per year for qualifying patients.",
     "features": ["Extra-depth design", "3 custom inserts included", "One pair/year Medicare benefit"]},
    {"slug": "lancets-100", "name": "Sterile Lancets (100 ct)", "category_slug": "diabetes-care", "coverage": "cash", "price": 9.99, "image": IMG["supplies"], "featured": False, "in_stock": True,
     "description": "30-gauge sterile lancets, compatible with most lancing devices.",
     "features": ["30 gauge ultra-thin", "Universal fit", "Resupply eligible"]},
    # Wound Care
    {"slug": "foam-dressings", "name": "Silicone Foam Dressings (10 ct)", "category_slug": "wound-care", "coverage": "insurance", "price": None, "image": IMG["wound"], "featured": True, "in_stock": True,
     "description": "Absorbent bordered foam dressings for pressure ulcers and surgical wounds. Covered under Medicare surgical dressing benefit.",
     "features": ["Gentle silicone border", "4\" x 4\" size", "Up to 7-day wear", "Resupply eligible"]},
    {"slug": "alginate-dressings", "name": "Calcium Alginate Dressings", "category_slug": "wound-care", "coverage": "insurance", "price": None, "image": IMG["wound"], "featured": False, "in_stock": True,
     "description": "Highly absorbent dressings for moderate-to-heavy draining wounds.",
     "features": ["Highly absorbent", "Conforms to wound bed", "Physician order required"]},
    {"slug": "gauze-rolls", "name": "Sterile Gauze Rolls (12 pk)", "category_slug": "wound-care", "coverage": "cash", "price": 14.99, "image": IMG["supplies"], "featured": False, "in_stock": True,
     "description": "Stretch gauze bandage rolls for securing dressings.",
     "features": ["4\" x 4.1 yd rolls", "Individually wrapped", "Latex free"]},
    {"slug": "medical-tape-kit", "name": "Wound Care Starter Kit", "category_slug": "wound-care", "coverage": "cash", "price": 24.99, "image": IMG["medical"], "featured": False, "in_stock": True,
     "description": "Complete kit: gauze pads, paper tape, saline wipes and scissors.",
     "features": ["20 gauze pads", "Hypoallergenic tape", "Travel case included"]},
]

FAQS = [
    {"question": "Does Medicare cover my medical equipment?", "question_es": "¿Medicare cubre mi equipo médico?", "answer": "Medicare Part B covers durable medical equipment (DME) like wheelchairs, walkers, glucose monitors and hospital beds when prescribed by your doctor and supplied by an accredited provider like CareFlex. You typically pay 20% of the Medicare-approved amount after your deductible.", "answer_es": "Medicare Parte B cubre equipos médicos duraderos (DME) como sillas de ruedas, andadores y monitores de glucosa cuando son recetados por su médico y suministrados por un proveedor acreditado como CareFlex. Generalmente paga el 20% del monto aprobado por Medicare después de su deducible.", "order": 1},
    {"question": "What do I need to get started?", "question_es": "¿Qué necesito para comenzar?", "answer": "Just three things: your insurance card, your doctor's contact information, and a prescription (we can help request it from your doctor). Complete our secure intake form or call us at +1 346-636-0201 #800 and we handle the rest.", "answer_es": "Solo tres cosas: su tarjeta de seguro, la información de contacto de su médico y una receta (podemos ayudar a solicitarla). Complete nuestro formulario seguro o llámenos al +1 346-636-0201 #800.", "order": 2},
    {"question": "How long does delivery take?", "question_es": "¿Cuánto tarda la entrega?", "answer": "Most in-stock items are delivered within 2–5 business days after insurance verification. Urgent hospital discharge orders are prioritized — call us for same-week delivery options.", "answer_es": "La mayoría de los artículos en stock se entregan dentro de 2 a 5 días hábiles después de la verificación del seguro. Los pedidos urgentes de alta hospitalaria son prioritarios.", "order": 3},
    {"question": "Do you handle the insurance paperwork?", "question_es": "¿Se encargan del papeleo del seguro?", "answer": "Yes. Our team verifies your benefits, obtains prior authorizations, and works directly with your doctor's office to collect required documentation. You'll know your estimated out-of-pocket cost before anything ships.", "answer_es": "Sí. Nuestro equipo verifica sus beneficios, obtiene autorizaciones previas y trabaja directamente con el consultorio de su médico. Conocerá su costo estimado antes de que se envíe algo.", "order": 4},
    {"question": "Can I buy items without insurance?", "question_es": "¿Puedo comprar artículos sin seguro?", "answer": "Absolutely. Items marked with a 'Cash-Pay' badge can be purchased directly at transparent prices — no prescription or insurance needed for most of them.", "answer_es": "Por supuesto. Los artículos marcados con 'Pago Directo' se pueden comprar directamente a precios transparentes.", "order": 5},
    {"question": "What insurance plans do you accept?", "question_es": "¿Qué planes de seguro aceptan?", "answer": "We accept Medicare Part B, Medicare Advantage plans, Medicaid, and most major commercial insurers. Visit our Insurance page or call to verify your specific plan.", "answer_es": "Aceptamos Medicare Parte B, planes Medicare Advantage, Medicaid y la mayoría de las aseguradoras comerciales.", "order": 6},
    {"question": "How do resupply reminders work?", "question_es": "¿Cómo funcionan los recordatorios de reabastecimiento?", "answer": "For disposables like test strips, CGM sensors and wound dressings, you can opt in to email or text reminders when you're due for a resupply. It's free, non-medical, and you can unsubscribe anytime.", "answer_es": "Para desechables como tiras reactivas y apósitos, puede optar por recibir recordatorios por correo electrónico o mensaje de texto. Es gratis y puede cancelar en cualquier momento.", "order": 7},
    {"question": "Is my health information safe?", "question_es": "¿Está segura mi información de salud?", "answer": "Yes. All protected health information is collected only through our HIPAA-compliant intake form (Jotform HIPAA under a signed BAA). Our website forms never ask for medical details.", "answer_es": "Sí. Toda la información de salud protegida se recopila únicamente a través de nuestro formulario HIPAA seguro. Los formularios de nuestro sitio web nunca solicitan detalles médicos.", "order": 8},
]

TESTIMONIALS = [
    {"name": "Margaret H.", "location": "Houston, TX", "rating": 5, "text": "CareFlex handled everything with Medicare for my husband's wheelchair. It arrived in four days and the delivery team showed us how to use it. Wonderful people.", "text_es": "CareFlex se encargó de todo con Medicare para la silla de ruedas de mi esposo. Llegó en cuatro días.", "order": 1},
    {"name": "Robert D.", "location": "Katy, TX", "rating": 5, "text": "I was drowning in paperwork trying to get my mother a rollator. One call to CareFlex and they took over — approved and delivered in a week.", "text_es": "Una llamada a CareFlex y se encargaron de todo: aprobado y entregado en una semana.", "order": 2},
    {"name": "Linda S., RN", "location": "Case Manager, Houston Methodist", "rating": 5, "text": "As a discharge planner, I need DME suppliers who respond fast. CareFlex confirms referrals same-day and keeps our patients out of the gap.", "text_es": "Como planificadora de altas, necesito proveedores que respondan rápido. CareFlex confirma las referencias el mismo día.", "order": 3},
    {"name": "Carlos M.", "location": "Sugar Land, TX", "rating": 5, "text": "The resupply reminders for my test strips are a lifesaver. I get a text, reply yes, and they ship. Never run out anymore.", "text_es": "Los recordatorios de reabastecimiento para mis tiras reactivas me salvan. Recibo un texto, respondo sí y las envían.", "order": 4},
]

SERVICE_AREAS = [
    {"name": "Harris County", "cities": "Houston, Pasadena, Baytown, Spring, Cypress, Katy (east)", "order": 1},
    {"name": "Fort Bend County", "cities": "Sugar Land, Missouri City, Richmond, Rosenberg, Katy (south)", "order": 2},
    {"name": "Montgomery County", "cities": "The Woodlands, Conroe, Magnolia, Willis", "order": 3},
    {"name": "Brazoria County", "cities": "Pearland, Alvin, Angleton, Lake Jackson", "order": 4},
    {"name": "Galveston County", "cities": "League City, Texas City, Galveston, Friendswood", "order": 5},
    {"name": "Liberty County", "cities": "Liberty, Dayton, Cleveland", "order": 6},
    {"name": "Waller County", "cities": "Waller, Hempstead, Prairie View", "order": 7},
    {"name": "Chambers County", "cities": "Mont Belvieu, Anahuac, Winnie", "order": 8},
]

POSTS = [
    {"slug": "medicare-dme-coverage-guide", "title": "Your 2026 Guide to Medicare DME Coverage", "category": "Insurance", "author": "CareFlex Team", "image": IMG["doctor"],
     "excerpt": "What Medicare Part B covers, what you'll pay, and how to qualify for a wheelchair, walker, or glucose monitor.",
     "content": "Medicare Part B covers durable medical equipment (DME) when it is medically necessary and prescribed by your doctor for use in your home.\n\n## What counts as DME?\nWheelchairs, walkers, hospital beds, blood glucose monitors, CPAP machines, and certain orthotic braces all qualify. The equipment must withstand repeated use, serve a medical purpose, and be appropriate for home use.\n\n## What will I pay?\nAfter you meet your Part B deductible, you typically pay 20% of the Medicare-approved amount. If you have a Medigap or Medicare Advantage plan, your share may be lower — our team verifies this for you before anything ships.\n\n## The 3 steps to coverage\n1. **See your doctor.** You need a face-to-face visit and a written order.\n2. **Choose an accredited supplier.** Medicare only pays claims from accredited suppliers like CareFlex.\n3. **We handle the paperwork.** We collect the documentation, bill Medicare, and deliver to your door.\n\nQuestions? Call us at +1 346-636-0201 #800 — we're happy to check your coverage at no cost.",
     "seo_title": "Medicare DME Coverage Guide 2026 | CareFlex", "seo_description": "Learn what durable medical equipment Medicare Part B covers, what you'll pay, and how to qualify.", "published": True},
    {"slug": "choosing-the-right-walker", "title": "Walker vs. Rollator: Which Is Right for You?", "category": "Mobility", "author": "CareFlex Team", "image": IMG["walker"],
     "excerpt": "A simple comparison to help you or your loved one pick the safest mobility aid.",
     "content": "Choosing between a standard walker and a rollator comes down to balance, strength, and where you'll use it.\n\n## Standard walkers\nBest for people who need to put weight on the frame. They're lighter, more stable, and covered by Medicare with a prescription. The trade-off: you must lift or slide them with each step.\n\n## Rollators (wheeled walkers)\nBest for people with fair balance who tire easily. Four wheels, hand brakes, and a built-in seat let you walk farther and rest when needed.\n\n## Quick checklist\n- Need to lean heavily? → Standard walker\n- Walk longer distances outdoors? → Rollator\n- Need to rest often? → Rollator with seat\n- Narrow doorways at home? → Standard walker (usually slimmer)\n\nOur team can help you decide — call +1 346-636-0201 #800 or complete our intake form and we'll match the right equipment to your needs and coverage.",
     "seo_title": "Walker vs Rollator Comparison | CareFlex", "seo_description": "Compare standard walkers and rollators to find the safest mobility aid for you or a loved one.", "published": True},
    {"slug": "diabetes-supplies-through-medicare", "title": "How to Get Diabetes Supplies Through Medicare", "category": "Diabetes", "author": "CareFlex Team", "image": IMG["diabetes"],
     "excerpt": "Test strips, CGMs, and therapeutic shoes — what's covered and how resupply works.",
     "content": "If you have diabetes and Medicare Part B, you're entitled to more coverage than most people realize.\n\n## Covered supplies\n- Blood glucose meters and test strips\n- Lancets and lancing devices\n- Continuous glucose monitors (CGMs) for qualifying patients\n- Therapeutic shoes and inserts (one pair per year)\n\n## How much can I get?\nQuantity limits depend on whether you use insulin. Insulin users can typically receive up to 300 strips every 3 months; non-insulin users up to 100.\n\n## Never run out again\nCareFlex offers free resupply reminders by text or email. When your resupply date approaches, we send a quick reminder — reply and your supplies ship. Opt in on any diabetes product page.\n\nCall +1 346-636-0201 #800 to verify your coverage in minutes.",
     "seo_title": "Medicare Diabetes Supplies Guide | CareFlex", "seo_description": "How to get glucose test strips, CGMs, and diabetic shoes covered through Medicare Part B.", "published": True},
]
